batch_size: 2
data_path: /home/marcel/workspace/datasets
# /home/marcel/workspace/datasets
# C:\Users\marce\Documents\datasets
dataset: ameise
explore_data: false
grid_step: 8
img_height: null
img_width: null
inspect_model: true
learning_rate: 0.001
load_weights: false
logging:
  activate: true
  project: Stixel-Multicut
loss:
  alpha: 1.0
  beta: 1.0
  gamma: false
nn:
  depths:
  - 6
  - 3
  drop_p: 0.0
  stem_features: 64
  widths:
  - 96
  - 192
  - 384
  - 768
num_epochs: 40
pred_threshold: 0.4
evaluation:
  iou: 0.5
  num_thresholds: 10
  model: StixelNExT
resources:
  test_worker: 2
  train_worker: 2
  val_worker: 2
test_loss: true
training: true
weights_file: StixelNExT_volcanic-spaceship-170_epoch-31_test-error-0.2544909715652466.pth
