prediction_folder: /home/marcel/workspace/datasets/ameise/testing/predictions_from_StixelNExT/StixelNExT_rose-energy-117_epoch-12_test-error-0.19930797815322876
# StixelNExT: /home/marcel/workspace/datasets/ameise/testing/predictions_from_StixelNExT/StixelNExT_rose-energy-117_epoch-12_test-error-0.19930797815322876
# /home/marcel/workspace/datasets/ameise/testing/predictions_from_stereo
num_thresholds: 10    # from 0 to 1, for pr-curve e.g. it is the IoU
dataset: ameise       # logging info
logging:
  activate: True
  project: Stixel-Multicut
